// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qdea.API.Models;

namespace Qdea.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20201215162235_EfMigration")]
    partial class EfMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Qdea.API.Domain.AddedUser", b =>
                {
                    b.Property<int>("AddedUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("IdeaID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AddedUserID");

                    b.HasIndex("IdeaID");

                    b.HasIndex("UserID");

                    b.ToTable("AddedUsers");
                });

            modelBuilder.Entity("Qdea.API.Domain.Effort", b =>
                {
                    b.Property<int>("EffortID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EffortID");

                    b.ToTable("Efforts");
                });

            modelBuilder.Entity("Qdea.API.Domain.Idea", b =>
                {
                    b.Property<int>("IdeaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastEdited")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EffortID")
                        .HasColumnType("int");

                    b.Property<int?>("IdeaStatusID")
                        .HasColumnType("int");

                    b.Property<int?>("ImpactID")
                        .HasColumnType("int");

                    b.Property<int?>("PriorityID")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("IdeaID");

                    b.HasIndex("EffortID");

                    b.HasIndex("IdeaStatusID");

                    b.HasIndex("ImpactID");

                    b.HasIndex("PriorityID");

                    b.HasIndex("UserID");

                    b.ToTable("Ideas");
                });

            modelBuilder.Entity("Qdea.API.Domain.IdeaInteraction", b =>
                {
                    b.Property<int>("IdeaInteractionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdeaID")
                        .HasColumnType("int");

                    b.Property<int?>("IdeaInteractionTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastDateTimeEdited")
                        .HasColumnType("datetime2");

                    b.Property<string>("TextContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("IdeaInteractionID");

                    b.HasIndex("IdeaID");

                    b.HasIndex("IdeaInteractionTypeID");

                    b.HasIndex("UserID");

                    b.ToTable("IdeaInteractions");
                });

            modelBuilder.Entity("Qdea.API.Domain.IdeaInteractionType", b =>
                {
                    b.Property<int>("IdeaInteractionTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdeaInteractionTypeID");

                    b.ToTable("IdeaInteractionTypes");
                });

            modelBuilder.Entity("Qdea.API.Domain.IdeaStatus", b =>
                {
                    b.Property<int>("IdeaStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdeaStatusID");

                    b.ToTable("IdeaStatuses");
                });

            modelBuilder.Entity("Qdea.API.Domain.Impact", b =>
                {
                    b.Property<int>("ImpactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImpactID");

                    b.ToTable("Impacts");
                });

            modelBuilder.Entity("Qdea.API.Domain.Priority", b =>
                {
                    b.Property<int>("PriorityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PriorityID");

                    b.ToTable("Priorities");
                });

            modelBuilder.Entity("Qdea.API.Domain.Tag", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagID");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Qdea.API.Domain.TagIdea", b =>
                {
                    b.Property<int>("TagListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("IdeaID")
                        .HasColumnType("int");

                    b.Property<int?>("TagID")
                        .HasColumnType("int");

                    b.HasKey("TagListID");

                    b.HasIndex("IdeaID");

                    b.HasIndex("TagID");

                    b.ToTable("TagIdeas");
                });

            modelBuilder.Entity("Qdea.API.Domain.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<int?>("UserStatusID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("UserStatusID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Qdea.API.Domain.UserStatus", b =>
                {
                    b.Property<int>("UserStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserStatusID");

                    b.ToTable("UserStatuses");
                });

            modelBuilder.Entity("Qdea.API.Domain.AddedUser", b =>
                {
                    b.HasOne("Qdea.API.Domain.Idea", "Idea")
                        .WithMany()
                        .HasForeignKey("IdeaID");

                    b.HasOne("Qdea.API.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("Idea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Qdea.API.Domain.Idea", b =>
                {
                    b.HasOne("Qdea.API.Domain.Effort", "Effort")
                        .WithMany()
                        .HasForeignKey("EffortID");

                    b.HasOne("Qdea.API.Domain.IdeaStatus", "IdeaStatus")
                        .WithMany()
                        .HasForeignKey("IdeaStatusID");

                    b.HasOne("Qdea.API.Domain.Impact", "Impact")
                        .WithMany()
                        .HasForeignKey("ImpactID");

                    b.HasOne("Qdea.API.Domain.Priority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityID");

                    b.HasOne("Qdea.API.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("Effort");

                    b.Navigation("IdeaStatus");

                    b.Navigation("Impact");

                    b.Navigation("Priority");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Qdea.API.Domain.IdeaInteraction", b =>
                {
                    b.HasOne("Qdea.API.Domain.Idea", "Idea")
                        .WithMany()
                        .HasForeignKey("IdeaID");

                    b.HasOne("Qdea.API.Domain.IdeaInteractionType", "IdeaInteractionType")
                        .WithMany()
                        .HasForeignKey("IdeaInteractionTypeID");

                    b.HasOne("Qdea.API.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("Idea");

                    b.Navigation("IdeaInteractionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Qdea.API.Domain.TagIdea", b =>
                {
                    b.HasOne("Qdea.API.Domain.Idea", "Idea")
                        .WithMany()
                        .HasForeignKey("IdeaID");

                    b.HasOne("Qdea.API.Domain.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagID");

                    b.Navigation("Idea");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Qdea.API.Domain.User", b =>
                {
                    b.HasOne("Qdea.API.Domain.UserStatus", "UserStatus")
                        .WithMany()
                        .HasForeignKey("UserStatusID");

                    b.Navigation("UserStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
